# Generated by Django 5.2.8 on 2025-11-10 12:20

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Document title", max_length=255)),
                ("file", models.FileField(help_text="PDF file", upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Redaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "redaction_type",
                    models.CharField(
                        choices=[("text", "Text Selection"), ("area", "Area Drawing")],
                        help_text="Type of redaction (text selection or area drawing)",
                        max_length=10,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(help_text="Redaction coordinates in format: {x, y, width, height, page}"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Associated document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redactions",
                        to="redaction.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "created_at"],
            },
        ),
    ]
